name: anime_app
description: Final project of the course Development of mobile devices
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  sqflite: ^2.2.8+4
  path: ^1.8.3 
  shared_preferences: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
